POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "reilleygray@gmail.com",
  "password": "password",
  "firstName": "Reilley",
  "lastName": "Gray"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "reilleygray@gmail.com",
  "password": "password"
}

###

POST http://localhost:8080/assets
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyZWlsbGV5Z3JheUBnbWFpbC5jb20iLCJleHAiOjE1ODQ0MDYyMTV9.i7l6y3Goyfmf_5P5gAjmrewkqEo__B-pwdoFOXL8Hb2a0DfJxnnmrkAeQVlDzwOZfA6ZGe-ZhFb6VJhsG445jw

{
  "symbol": "SNE"
}

###