POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "reilleygray@gmail.com",
  "password": "password",
  "firstName": "Reilley",
  "lastName": "Gray"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "reilleygray@gmail.com",
  "password": "password"
}

###

GET http://localhost:8080/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyZWlsbGV5Z3JheUBnbWFpbC5jb20iLCJleHAiOjE1ODQ2OTAyNTZ9.s5L4XxzzPRtTI1-i58U7vP1vYAyhgnIU4A3bo2G4FwlTCKsLryuRYeCqHsPhR4mLovudbvKsuNjUAvQLWZj8Hg

###

POST http://localhost:8080/stocks
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyZWlsbGV5Z3JheUBnbWFpbC5jb20iLCJleHAiOjE1ODQ3MDMzNDF9.QG4EZ5w4JaOV0lv2UxowAk5kc_7kM0p86SF_j5GpcXRUPfEv6wLGeQwFJVPjQ4dRriNqP0P7iqrBUaYz6CQZtQ

{
  "symbol": "NVDA"
}

###