POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "reilleygray@gmail.com",
  "password": "password",
  "firstName": "Reilley",
  "lastName": "Gray"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "reilleygray@gmail.com",
  "password": "password"
}

###

GET http://localhost:8080/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyZWlsbGV5Z3JheUBnbWFpbC5jb20iLCJleHAiOjE1ODQ2OTAyNTZ9.s5L4XxzzPRtTI1-i58U7vP1vYAyhgnIU4A3bo2G4FwlTCKsLryuRYeCqHsPhR4mLovudbvKsuNjUAvQLWZj8Hg

###

POST http://localhost:8080/stocks
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyZWlsbGV5Z3JheUBnbWFpbC5jb20iLCJleHAiOjE1ODQ3OTA3NjN9.vxRu9bScsluIHHkLld-MAqoybWpx4zAuTc_ro7FONXziq5qZ3_dskgow7dMI-CVm-Ygv5jjg3eBjXzzJH5Wycg

{
  "symbol": "TSLA"
}

###